-- 0044_webhook_token.sql
-- M7.2.3-B.1: Webhook tenant routing hardening.
--
-- Adds a webhook_token column to carrier_credentials.
-- This token is a random, URL-safe identifier used in webhook URLs:
--   POST /v1/webhooks/carrier/:providerKey/:webhookToken
--
-- The token uniquely identifies a credential row (and thus an org+provider),
-- enabling multi-org webhook routing without ambiguity.
--
-- Backward compatible: existing :providerKey-only route still works.
-- The token is auto-generated on insert via gen_random_uuid() for existing rows.
-- New rows get a token generated by the application layer.

-- Add the webhook_token column (nullable for backward compat during migration)
ALTER TABLE carrier_credentials
  ADD COLUMN IF NOT EXISTS webhook_token VARCHAR(64);

-- Generate tokens for existing rows
UPDATE carrier_credentials
  SET webhook_token = 'whk_' || replace(gen_random_uuid()::text, '-', '')
  WHERE webhook_token IS NULL;

-- Now make it NOT NULL with a default
ALTER TABLE carrier_credentials
  ALTER COLUMN webhook_token SET NOT NULL;

ALTER TABLE carrier_credentials
  ALTER COLUMN webhook_token SET DEFAULT 'whk_' || replace(gen_random_uuid()::text, '-', '');

-- Unique index for webhook token lookups
CREATE UNIQUE INDEX IF NOT EXISTS uq_carrier_creds_webhook_token
  ON carrier_credentials(webhook_token);
