name: mobile_core
description: Shared Flutter core library for SCS mobile
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
